// app/(view)/admin/(panel)/events/eventsStyles.js

const styles = {
  cardOuter: {
    background: "#ffffff",
    borderRadius: 16,
    border: "1px solid #e6eeff",
    boxShadow:
      "0 10px 40px rgba(11, 86, 201, 0.07), 0 3px 12px rgba(11,86,201,0.05)",
    overflow: "hidden",
  },
  cardHeaderBar: {
    height: 20,
    background:
      "linear-gradient(90deg, #0b56c9 0%, #0b56c9 65%, rgba(11,86,201,0.35) 100%)",
  },
  cardInner: { padding: "12px 14px 14px", position: "relative" },
  cardTitle: {
    fontSize: 18,
    fontWeight: 800,
    color: "#0b3e91",
    marginTop: 8,
    marginBottom: 8,
  },
  totalBadgeWrap: {
    position: "absolute",
    right: 14,
    top: 8,
    display: "grid",
    gap: 4,
    justifyItems: "end",
    background: "#fff",
    border: "1px solid #e6eeff",
    borderRadius: 12,
    padding: "6px 12px",
    boxShadow: "0 6px 18px rgba(11,86,201,0.08)",
  },
  totalBadgeLabel: { fontSize: 12, color: "#0b3e91", fontWeight: 600 },
  totalBadgeValue: {
    fontSize: 16,
    color: "#0b56c9",
    fontWeight: 800,
    lineHeight: 1,
  },

  statsRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: 14,
    marginTop: 12,
  },
  statCard: {
    background: "#fff",
    borderRadius: 14,
    border: "1px solid #e6eeff",
    boxShadow: "0 10px 24px rgba(11,86,201,0.08)",
    padding: "12px 16px",
    display: "grid",
    gridTemplateColumns: "48px 1fr auto",
    alignItems: "center",
    columnGap: 12,
  },
  statIconBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    border: "1px solid #e6eeff",
    background: "#f8fbff",
    display: "grid",
    placeItems: "center",
    boxShadow: "inset 0 2px 8px rgba(11,86,201,0.06)",
  },
  statIconImg: { width: 28, height: 28, objectFit: "contain" },
  statTitle: { fontWeight: 800, color: "#0b3e91", textAlign: "center" },
  statValue: { fontWeight: 800, fontSize: 24, color: "#0b56c9" },

  sectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  sectionTitle: { fontSize: 18, fontWeight: 800, color: "#0b3e91" },

  filtersRowBig: {
    display: "grid",
    gridTemplateColumns: "1fr 140px minmax(220px, 1fr) auto auto auto",
    gap: 8,
    alignItems: "center",
  },
  searchInput: { height: 36, borderRadius: 10 },

  chartsGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 },
  chartCard: {
    background: "#fff",
    border: "1px solid #e6eeff",
    borderRadius: 14,
    padding: "12px",
  },
  chartTitle: { fontWeight: 800, color: "#0b3e91", marginBottom: 8 },
  barsArea: {
    display: "grid",
    gridTemplateColumns: "repeat(8, minmax(0, 1fr))",
    gap: 10,
    height: 220, // fixed height so percentage-based bars can resolve
    alignItems: "stretch",
  },
  barItem: {
    display: "grid",
    gridTemplateRows: "minmax(0, 1fr) auto",
    gap: 6,
    justifyItems: "center",
    height: "100%",
  },
  barCol: {
    width: "100%",
    height: "100%",
    background: "linear-gradient(180deg,#f3f7ff 0%,#fbfdff 100%)",
    border: "1px solid #e6eeff",
    borderRadius: 10,
    display: "flex",
    alignItems: "flex-end",
    padding: 4,
  },
  barInner: {
    width: "100%",
    borderRadius: 8,
    background:
      "linear-gradient(180deg, rgba(11,86,201,0.8) 0%, rgba(11,86,201,0.45) 100%)",
    boxShadow: "0 3px 10px rgba(11,86,201,0.25)",
  },
  barInnerAlt: {
    width: "100%",
    borderRadius: 8,
    background:
      "linear-gradient(180deg, rgba(9,132,71,0.85) 0%, rgba(9,132,71,0.45) 100%)",
    boxShadow: "0 3px 10px rgba(9,132,71,0.25)",
  },
  barLabel: {
    fontSize: 11.5,
    color: "#475569",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: "100%",
  },

  tableHeader: {
    display: "grid",
    gridTemplateColumns: "1.6fr .8fr 1.2fr 1fr .8fr .7fr .9fr",
    gap: 8,
    marginBottom: 4,
    color: "#0b3e91",
    fontWeight: 700,
    alignItems: "center",
    minWidth: 1060,
  },
  thLeft: { display: "flex", justifyContent: "flex-start", width: "100%" },
  thCenter: { display: "flex", justifyContent: "center", width: "100%" },

  row: {
    display: "grid",
    gridTemplateColumns: "1.6fr .8fr 1.2fr 1fr .8fr .7fr .9fr",
    gap: 8,
    alignItems: "center",
    background: "#f5f8ff",
    borderRadius: 10,
    border: "1px solid #e8eeff",
    padding: "8px 10px",
    boxShadow: "0 6px 12px rgba(11, 86, 201, 0.05)",
    minWidth: 1060,
  },

  colName: {
    background: "#ffffff",
    borderRadius: 10,
    border: "1px solid #eef3ff",
    padding: "6px 10px",
    display: "flex",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
  },
  nameWrap: { display: "grid", gap: 2, minWidth: 0 },
  nameText: {
    fontWeight: 600,
    color: "#111827",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  subDate: { fontSize: 11.5, color: "#6b7280" },

  colCenter: {
    textAlign: "center",
    color: "#0f172a",
    fontWeight: 600,
    minWidth: 0,
  },
  cellEllipsis: {
    display: "inline-block",
    maxWidth: "100%",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    verticalAlign: "bottom",
  },
  colActionsCenter: { display: "flex", justifyContent: "center", gap: 6 },
  iconBtn: { borderRadius: 8 },

  pagination: {
    marginTop: 12,
    display: "grid",
    gridTemplateColumns: "36px 1fr 36px",
    alignItems: "center",
    justifyItems: "center",
    gap: 8,
  },
  pageText: { fontSize: 12, color: "#475569" },

  label: { fontSize: 11.5, color: "#64748b" },
  value: {
    fontWeight: 600,
    color: "#0f172a",
    background: "#f8fafc",
    border: "1px solid #e8eeff",
    borderRadius: 10,
    padding: "8px 10px",
    boxShadow: "inset 0 2px 6px rgba(11,86,201,0.05)",
    wordBreak: "break-word",
  },
  modalShell: {
    position: "relative",
    background: "#fff",
    borderRadius: 16,
    padding: "14px 14px 8px",
    boxShadow: "0 10px 36px rgba(11,86,201,0.08)",
  },

  coverWrap: {
    display: "grid",
    justifyContent: "center",
    justifyItems: "center",
    marginTop: 6,
    marginBottom: 10,
  },
  coverBox: {
    width: "100%",
    height: "100%",
    borderRadius: 12,
    border: "2px dashed #c0c8d8",
    background: "#f8fbff",
    display: "grid",
    placeItems: "center",
    overflow: "hidden",
  },
  coverImg: { width: "100%", height: "100%", objectFit: "cover" },
  coverPlaceholder: { fontWeight: 700, color: "#0b56c9", userSelect: "none" },

  modalFooter: { marginTop: 8, display: "grid", placeItems: "center" },
  saveBtn: { minWidth: 200, height: 40, borderRadius: 12 },
};

export default styles;
